import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"
import React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import { ThemeProvider } from "@/components/feature/theme-provider";
import { Globe, Menu, Search } from "lucide-react";
import ThemeToggle from "@/components/feature/theme-toggle";
import UserMenu from "@/components/feature/user-menu";
import NotificationMenu from "@/components/feature/notification-menu";
import DesktopNavigation from "@/components/feature/desktop-navigation";
import MobileNavigation from "@/components/feature/mobile-navigation";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    fontSans.variable
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
                        <div className="hidden border-r bg-muted/40 md:block">
                            <div className="flex h-full max-h-screen flex-col gap-2">
                                <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
                                    <Link href="/" className="flex items-center gap-2 font-semibold">
                                        <Globe className="h-6 w-6"/>
                                        <span>Sphere</span>
                                    </Link>
                                </div>

                                <div className="flex-1">
                                    <DesktopNavigation/>
                                </div>
                            </div>
                        </div>

                        <div className="flex flex-col">
                            <header className="flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6">
                                <Sheet>
                                    <SheetTrigger asChild>
                                        <Button
                                            variant="outline"
                                            size="icon"
                                            className="shrink-0 md:hidden"
                                        >
                                            <Menu className="h-5 w-5"/>
                                            <span className="sr-only">Toggle navigation menu</span>
                                        </Button>
                                    </SheetTrigger>

                                    <SheetContent side="left" className="flex flex-col">
                                        <MobileNavigation/>
                                    </SheetContent>
                                </Sheet>

                                <div className="w-full flex-1">
                                    <form>
                                        <div className="relative">
                                            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"/>
                                            <Input
                                                type="search"
                                                placeholder="Search products..."
                                                className="w-full appearance-none bg-background pl-8 shadow-none md:w-2/3 lg:w-1/3"
                                            />
                                        </div>
                                    </form>
                                </div>

                                <div className="flex items-center gap-1">
                                    <ThemeToggle />
                                    <NotificationMenu />
                                    <UserMenu />
                                </div>
                            </header>

                            <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
                                {children}
                            </main>
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
